// ============================================
// CRACKSHOT 공연 데이터
// 새 공연을 추가하려면 이 배열 맨 위에
// { ... } 객체를 하나 복사해서 붙여넣고 내용만 바꾸면 됩니다.
// ============================================

const CONCERTS = [
  {
    id: "2026-07-31",
    date: "2026-07-31",
    title: "2026 장흥 ROCK 페스티벌",
    venue: "장흥 물축제",
    photoUrl: "null",
    setlist: [
      "UNKNOWN"
    ]
  },
  {
    id: "2026-07-25",
    date: "2026-07-25",
    title: "HAIL TO THE KING",
    venue: "홍대 클럽FF",
    photoUrl: "null",
    setlist: [
      "UNKNOWN"
    ]
  },
  {
    id: "2026-07-19",
    date: "2026-07-19",
    title: "STILL ROLLING Vol.4",
    venue: "홍대 BENDER",
    photoUrl: "null",
    setlist: [
      "UNKNOWN"
    ]
  },
  {
    id: "2026-07-10",
    date: "2026-07-10",
    title: "문래동 프리덤",
    venue: "문래 후케즈",
    photoUrl: "https://www.instagram.com/p/DanYcARgSuZ/?utm_source=ig_web_copy_link",
    setlist: [
      "Get Over",
      "LOUD! HOT! CRAZY!",
      "Puppeteer",
      "Bang Your Head",
      "Young & Wild",
      "INFP",
      "Follow Me",
      "Kickstart My Heart"
    ]
  },
  {
    id: "2026-06-27",
    date: "2026-06-27",
    title: "Live Club Day",
    venue: "홍대 클럽FF",
    photoUrl: "https://www.instagram.com/p/DaDf06LAfFn/?utm_source=ig_web_copy_link",
    setlist: [
      "Young & Wild",
      "Get Over",
      "DASH",
      "Puppeteer",
      "Take it down",
      "Shake It!",
      "INFP",
      "LOUD! HOT! CRAZY!",
      "Follow Me",
      "Paradise city"
    ]
  },
  {
    id: "2026-06-05",
    date: "2026-06-05",
    title: "크랙샷 X 더픽스 Our Target",
    venue: "홍대 웨스트브릿지",
    photoUrl: "https://www.instagram.com/p/DZO4GYDEcxg/?utm_source=ig_web_copy_link",
    setlist: [
      "Young & Wild",
      "Get Over",
      "LOUD! HOT! CRAZY!",
      "Warriors",
      "FIRE",
      "Time To Rise",
      "Shake It!",
      "Overdrive",
      "Bye Goodbye",
      "Follow Me",
      "INFP",
      "Don't Stop Believin",
      "Don't Look Back"
    ]
  },
  {
    id: "2026-04-25",
    date: "2026-04-25",
    title: "2026 Hero Rock Festival",
    venue: "마포 문화비축기지",
    photoUrl: "https://www.instagram.com/p/DXi0UCVkWqk/?utm_source=ig_web_copy_link",
    setlist: [
      "Go Away",
      "Young & Wild",
      "Get Over",
      "Overdrive",
      "LOUD! HOT! CRAZY!",
      "Shake It!",
      "INFP",
      "Follow Me"
    ]
  },
    {
    id: "2026-04-17",
    date: "2026-04-17",
    title: "2026 ONE HOUR 4월",
    venue: "부산 상상마당",
    photoUrl: "https://www.instagram.com/p/DXO7xQggeRL/?utm_source=ig_web_copy_link",
    setlist: [
      "Go Away",
      "Get Over",
      "Young & Wild",
      "Overdrive",
      "Midnight Crime",
      "Don't Close Your Eyes",
      "Time To Rise",
      "My Friend",
      "Shake It!",
      "Slow Motion",
      "INFP",
      "LOUD! HOT! CRAZY!",
      "Bye Goodbye",
      "Break Down",
      "Follow Me"
    ]
  },
  {
    id: "2026-03-13",
    date: "2026-03-13",
    title: "크랙샷 단독 콘서트 백열",
    venue: "홍대 웨스트브릿지",
    photoUrl: "https://www.instagram.com/p/DV1BEBDAdJe/?utm_source=ig_web_copy_link",
    setlist: [
      "Go Away",
      "DASH",
      "Get Over",
      "Young & Wild",
      "Shake It!",
      "Night Rider",
      "Overdrive",
      "Party! Party!",
      "Suzie Q",
      "Slow Motion",
      "Slither",
      "Warriors",
      "The Show Must Go On",
      "Time To Rise",
      "Goodbye My Love",
      "Take it Down",
      "INFP",
      "LOUD! HOT! CRAZY!",
      "Bye Goodbye",
      "Break Down",
      "Follow Me"
    ]
  },
  {
    id: "2026-01-17",
    date: "2026-01-17",
    title: "너트 30 페스티벌",
    venue: "홍대 상상마당",
    photoUrl: "https://www.instagram.com/p/DTnYkL1gXAU/?utm_source=ig_web_copy_link",
    setlist: [
      "LOUD! HOT! CRAZY!",
      "Young & Wild",
      "Overdrive",
      "Shake It!",
      "INFP",
      "Follow Me",
      "Party! Party!",
      "넌 내게 반했어"
    ]
  },
    {
    id: "2025-12-24",
    date: "2025-12-24",
    title: "크랙샷 팬 콘서트 Merry CRACKSHOW",
    venue: "엠팟홀",
    photoUrl: "https://www.instagram.com/p/DSpm3nogV2C/?utm_source=ig_web_copy_link",
    setlist: [
      "Get Over",
      "LOUD! HOT! CRAZY!",
      "Fly me to the moon",
      "Bye Goodbye",
      "INFP",
      "Party! Party!",
      "Follow Me",
      "Feliz Navidad",
      "All I want for christmas is you",
    ]
  },
  {
    id: "2025-11-29",
    date: "2025-11-29",
    title: "히어로 in 인제 구상나무 숲길 홍보 콘서트",
    venue: "인제 구상나무숲",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DRoYOoAkaCo/",
    setlist: [
      "LOUD! HOT! CRAZY!",
      "Young & Wild",
      "DASH",
      "INFP",
      "Overdrive",
      "Follow Me",
    ]
  },
  {
    id: "2025-11-19",
    date: "2025-11-19",
    title: "경산 공감 락 페스티벌",
    venue: "천마아트센터 그랜드홀",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DRPS4QiAYrl/",
    setlist: [
      "Bye Goodbye",
      "LOUD! HOT! CRAZY!",
      "Young & Wild",
      "Shake It!",
      "INFP",
      "Follow Me",
      "Overdrive",
    ]
  },
  {
    id: "2025-10-17",
    date: "2025-10-17",
    title: "광주 버스킹 월드컵 32강",
    venue: "광주 국립아시아문화전당 하늘마당",
    setlist: [
      "The Show Must Go On",
      "LOUD! HOT! CRAZY!",
      "난 괜찮아",
      "아파트"
    ]
  },
  {
    id: "2025-10-18",
    date: "2025-10-18",
    title: "광주 버스킹 월드컵 16강",
    venue: "광주 국립아시아문화전당 하늘마당",
    setlist: [
      "Warriors",
      "FIRE",
      "Young & Wild",
      "Overdrive"
    ]
  },
 {
    id: "2025-10-19",
    date: "2025-10-19",
    title: "광주 버스킹 월드컵 결선",
    venue: "광주 국립아시아문화전당 하늘마당",
    setlist: [
      "Skyfall",
      "INFP"
    ]
 },
  {
    id: "2025-09-27",
    date: "2025-09-27",
    title: "양천 락 페스티벌",
    venue: "양천 신월야구장",
    setlist: [
      "Overdrive",
      "Young & Wild",
      "LOUD! HOT! CRAZY!",
      "INFP",
      "Follow Me",
    ]
  },
  {
    id: "2025-09-13",
    date: "2025-09-13",
    title: "사운드 플래닛 페스티벌 2025",
    venue: "인천 파라다이스시티",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DOiN1tAEZon/",
    setlist: [
      "LOUD! HOT! CRAZY!",
      "Young & Wild",
      "Shake It!",
      "Go Away",
      "Overdrive",
      "Slow Motion",
      "INFP",
      "Follow Me",
    ]
  },
  {
    id: "2025-09-10",
    date: "2025-09-10",
    title: "뒤란",
    venue: "울산 문화예술회관 야외공연장",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DObIrAygV6X/",
    setlist: [
      "Overdrive",
      "Get Over",
      "아파트",
      "LOUD! HOT! CRAZY!",
      "난 괜찮아",
    ]
  },
  {
    id: "2025-09-07",
    date: "2025-09-07",
    title: "2025 렛츠락 페스티벌",
    venue: "난지 한강공원",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DOSrVupkeIU/",
    setlist: [
      "LOUD! HOT! CRAZY!",
      "Young & Wild",
      "DASH",
      "Get Over",
      "Overdrive",
      "Shake It!",
      "INFP",
      "Follow Me",
    ]
  },
  {
    id: "2025-09-06",
    date: "2025-09-06",
    title: "2025 라이징스타를 찾아라 콘서트",
    venue: "동탄 복합문화센터 야외공연장",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DOQsRlNAXFw/",
    setlist: [
      "Overdrive",
      "Young & Wild",
      "INFP",
      "LOUD! HOT! CRAZY!",
      "Follow Me",
      "DASH",
    ]
  },
  {
    id: "2025-08-22",
    date: "2025-08-22",
    title: "서초 금요음악회 밴드 페스티벌 Rock The Night",
    venue: "서초 문화예술회관",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DNqGBPMhwIE/",
    setlist: [
      "Young & Wild",
      "DASH",
      "Get Over",
      "아파트",
      "예술이야",
      "난 괜찮아",
      "Shake It!",
      "INFP",
      "Skyfall",
      "Oops I did it again",
      "Still loving you",
      "Dream On",
      "그대에게+붉은노을+여행을떠나요",
      "LOUD! HOT! CRAZY!",
      "Follow Me",
    ]
  },
  {
    id: "2025-08-16",
    date: "2025-08-16",
    title: "거제 한화오션 오션하모니",
    venue: "거제 옥포수변공원",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DNajkm_ho-g/",
    setlist: [
      "아파트",
      "Go Away",
      "FIRE",
      "난 괜찮아",
      "INFP",
      "Follow Me",
      "달의 몰락",
    ]
  },
  {
    id: "2025-07-31",
    date: "2025-07-31",
    title: "2025 장흥 물 축제 락 페스티벌",
    venue: "장흥 물 축제",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DMzzKrkBHkI/",
    setlist: [
      "Young & Wild",
      "난 괜찮아",
      "아파트",
      "Break Down",
      "그대에게+붉은노을+여행을떠나요",
      "INFP",
      "Follow Me",
      "DASH",
      "Overdrive",
    ]
  },
  {
    id: "2025-07-12",
    date: "2025-07-12",
    title: "포항 락메탈 경연대회",
    venue: "포항 영일대 해수욕장",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DMAnIxZBKTk/",
    setlist: [
      "Young & Wild",
      "DASH",
      "Get Over",
      "그대에게+붉은노을+여행을떠나요",
      "INFP",
      "Go Away",
      "Overdrive",
      "Follow Me",
    ]
  },
  {
    id: "2025-07-11",
    date: "2025-07-11",
    title: "We Are Crackshot vol.5",
    venue: "홍대 웨스트브릿지",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DL-VcG9h1qG/",
    setlist: [
      "무녀도",
      "Time To Rise",
      "Going Under",
      "Drowning",
      "Walking On FIRE",
      "Midnight Crime",
      "Abracadabra",
      "Let Me Out",
      "Skyfall",
      "Oops I did it again",
      "Warriors",
      "FIRE",
      "Deep Inside",
      "Get Over",
      "Young & Wild",
      "Night Rider",
      "Go Away",
      "LOUD! HOT! CRAZY!",
      "Radioactive",
      "DASH",
      "Follow Me",
    ]
  },
  {
    id: "2025-06-14",
    date: "2025-06-14",
    title: "2025 MMC",
    venue: "영등포아트홀",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DK4rYjdBCdi/",
    setlist: [
      "Walking On FIRE",
      "Young & Wild",
      "Night Rider",
      "Shake It!",
      "Get Over",
      "Time To Rise",
      "Break Down",
      "Overdrive",
      "DASH",
      "INFP",
      "Follow Me",
    ]
  },
  {
    id: "2025-04-26",
    date: "2025-04-26",
    title: "라이엇키즈 10주년 The Kidz Are Alright",
    venue: "홍대 웨스트브릿지",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DI6Pu7DBJJl/",
    setlist: [
      "Time To Rise",
      "DASH",
      "Young & Wild",
      "Get Over",
      "Overdrive",
      "Follow Me",
    ]
  },
  {
    id: "2025-04-12",
    date: "2025-04-12",
    title: "군산 청소년 꿈애축제",
    venue: "군산 은파호수공원",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DIWDU3chq_E/",
    setlist: [
      "FIRE",
      "Get Over",
      "INFP",
      "Follow Me",
    ]
  },
  {
    id: "2025-04-05",
    date: "2025-04-05",
    title: "클럽투어 GET OVER - 서울",
    venue: "홍대 프리버드",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DIEMhK9BlhI/",
    setlist: [
      "Weekly Medley",
      "Young & Wild",
      "Night Rider",
      "DASH",
      "Walking On FIRE",
      "World On FIRE",
      "Go Away",
      "Shake It!",
      "INFP",
      "Time To Rise",
      "Faint",
      "Break Down",
      "Get Over",
      "LZ Medley",
      "Overdrive",
      "Have a nice day",
      "Paradise City",
      "Follow Me",
    ]
  },
  {
    id: "2025-03-30",
    date: "2025-03-30",
    title: "클럽투어 GET OVER - 대전",
    venue: "대전 인터플레이",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DH0sJ_cBlnP/",
    setlist: [
      "We will rock you",
      "Young & Wild",
      "Night Rider",
      "DASH",
      "Walking On FIRE",
      "Shout at the Devil",
      "Go Away",
      "Slow Motion",
      "INFP",
      "Don't Close Your Eyes",
      "Faint",
      "Break Down",
      "Get Over",
      "You could be mine",
      "Overdrive",
      "Kickstart my Heart",
      "Follow Me",
    ]
  },
  {
    id: "2025-03-29",
    date: "2025-03-29",
    title: "클럽투어 GET OVER - 광주",
    venue: "광주 보헤미안",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DHyGinzhEpV/",
    setlist: [
      "We will rock you",
      "Young & Wild",
      "Night Rider",
      "DASH",
      "Walking On FIRE",
      "Youth gone wild",
      "Go Away",
      "Shake It!",
      "INFP",
      "Don't Close Your Eyes",
      "Faint",
      "Break Down",
      "Get Over",
      "LZ Medley",
      "Overdrive",
      "Slither",
      "Follow Me",
    ]
  },
  {
    id: "2025-03-23",
    date: "2025-03-23",
    title: "클럽투어 GET OVER - 대구",
    venue: "대구 클럽헤비",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DHipDF2hA_h/",
    setlist: [
      "Young & Wild",
      "Night Rider",
      "DASH",
      "Ready To FIRE",
      "You give love a bad name",
      "Go Away",
      "Shake It!",
      "INFP",
      "My Friend",
      "Shine",
      "Break Down",
      "Get Over",
      "Party! Party!",
      "Suzie Q",
      "Overdrive",
      "난 괜찮아",
      "Follow Me",
    ]
  },
  {
    id: "2025-03-22",
    date: "2025-03-22",
    title: "클럽투어 GET OVER - 부산",
    venue: "부산 바이닐 언더그라운드",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DHgH59ehoGe/",
    setlist: [
      "Young & Wild",
      "Night Rider",
      "DASH",
      "Walking On FIRE",
      "Wild Side",
      "Go Away",
      "Shake It!",
      "INFP",
      "My Friend",
      "Shine",
      "Break Down",
      "Get Over",
      "World On FIRE",
      "Overdrive",
      "Paradise City",
      "Follow Me",
    ]
  },
  {
    id: "2025-02-21",
    date: "2025-02-21",
    title: "We Are Crackshot vol.4",
    venue: "CKL 스테이지",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DGVkzY2BTtX/",
    setlist: [
      "Walking On FIRE",
      "Young & Wild",
      "Night Rider",
      "DASH",
      "Shake It!",
      "INFP",
      "Slow Motion",
      "Dream On",
      "Warriors",
      "Faithfully",
      "Home Sweet Home",
      "Go Away",
      "The Greatest Show",
      "Break Down",
      "Get Over",
      "Overdrive",
      "무녀도",
      "Follow Me",
    ]
  },
  {
    id: "2025-02-10",
    date: "2025-02-10",
    title: "불후의 명곡 윤수일편",
    venue: "KBS 신관",
    setlist: [
      "아파트"
    ]
  },
  {
    id: "2025-01-05",
    date: "2025-01-05",
    title: "롤링홀 30주년 기념공연 CRACKSHOT",
    venue: "홍대 롤링홀",
    photoUrl: "https://www.instagram.com/crackshot_official/p/DEcYjHKhH4a/",
    setlist: [
      "Young & Wild",
      "Night Rider",
      "DASH",
      "Midnight Crime",
      "Shake It!",
      "INFP",
      "Slow Motion",
      "You",
      "Dream On",
      "Warriors",
      "Time To Rise",
      "Go Away",
      "난 괜찮아",
      "Break Down",
      "Party! Party!",
      "Suzie Q",
      "Overdrive",
      "Slither",
      "Bye Goodbye",
      "Follow Me",
    ]
  }
];
